[package]
name = "rls"
version = "0.1.0"
authors = ["Jonathan Turner <jturner@mozilla.com>"]

[dependencies]
cargo = { path = "../cargo" }
derive-new = "0.3"
env_logger = "0.3"
rust_lsp = { version = "0.6.0", git = "https://github.com/RustDT/RustLSP" }
log = "0.3"
racer = { git = "https://github.com/phildawes/racer" }
rls-span = { git = "https://github.com/nrc/rls-span" }
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
rls-vfs = { git = "https://github.com/nrc/rls-vfs", features = ["racer-impls"] }
rustfmt = { git = "https://github.com/rust-lang-nursery/rustfmt" }
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

[dependencies.hyper]
version = "0.9"
default-features = false
