[package]
name = "rls"
version = "0.1.0"
authors = ["Jonathan Turner <jturner@mozilla.com>"]

[dependencies]
log = "0.3.6"
racer = { git = "https://github.com/phildawes/racer" }
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
rls-vfs = { git = "https://github.com/nrc/rls-vfs" }
rustfmt = { git = "https://github.com/rust-lang-nursery/rustfmt" }
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
derive-new = "0.1"
libc = "0.2"

[dev-dependencies]
env_logger = "0.3.0"

[dependencies.hyper]
version = "0.9"
default-features = false
